controller:
  extraArgs:
    default-ssl-certificate: "${namespace}/nginx-tls"

  containerPort:
    http: 80
    https: 443

  service:
    targetPorts:
      http: http
      https: https
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
      service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
      service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: '60'
      service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
      # service.beta.kubernetes.io/aws-load-balancer-type: nlb
      external-dns.alpha.kubernetes.io/hostname: ${hostname}.
  publishService:
    enabled: true

  config:
    server-tokens: "false"
    use-forwarded-headers: "true"
    use-proxy-protocol: "true"
    set-real-ip-from: "${proxy_real_ip_cidr}"
    real-ip-header: "proxy_protocol"

  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: node.kubernetes.io/lifecycle
            operator: In
            values:
              - ondemand

rbac:
  create: true
